### ISSUE TITLE
اشتباه در نمایش روز

### ISSUE THREAD

**Issue by eshagh79** [graymind75/shams#4]
سلام همونطور که در تصویری که خودتون در این مخزن گذاشتید، عدد روز، یک شماره بیش‌تر از عدد درست هست. مثلا در همون تصویر نوشته امروز جمعه، ۸ مرداد هست، درحالی که جمعه ۷ مرداد هست.
یا مثلا همین الان که در ترمینال امتحان کردم:
 Emruz: Shanbeh  9  Mordad(4)  1401  Tabestan   
در صورتی که امروز شنبه، ۸ مرداد هست.

**Comment by ItsBenyaamin** [comment]
ممنون از اینکه اطلاع دادید. اصلاح شد.
