### ISSUE TITLE
macOS release ?

### ISSUE THREAD

**Issue by chromer030** [graymind75/shams#5]
Thank you for this useful tool.
Please provide macOS amd64 and arm64 release binaries.

**Comment by ItsBenyaamin** [comment]
unfortunately, I don't have macOS.
You can easily
- install rust with: https://rustup.rs
- clone the repository with the git command: git clone https://github.com/graymind75/shams
- move to the folder: cd shams
- execute build command: cargo build --release
- after build process done, go to target/release folder and the binary is there: shams

**Comment by chromer030** [comment]
Thank you for explanations.
